wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1649865240
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      4: 3.8.10
      5: 0.12.14
      8:
      - 5
epochs:
  desc: null
  value: 30
es:
  desc: null
  value: 4
kfold:
  desc: null
  value: 3
model:
  desc: null
  value: efficientnet-b2
only_reals:
  desc: null
  value: false
only_syn:
  desc: null
  value: true
real_data_path:
  desc: null
  value: /ISIC256/ISIC_pool/malignant_all/Cropped_resized/validation/
syn_data_path_ben:
  desc: null
  value: /ISIC256/ISIC256_ORIGINAL/synth100k_mal/img_dirs/imgs_dirs_ben/
syn_data_path_mal:
  desc: null
  value: /ISIC256/ISIC256_ORIGINAL/synth100k_mal/img_dirs/imgs_dirs_mal/
synt_n_imgs:
  desc: null
  value: '10000'
tags:
  desc: null
  value: whole isic
unbalanced:
  desc: null
  value: false
