wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1649839574
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 15
      - 16
      4: 3.8.10
      5: 0.12.14
      8:
      - 5
model:
  desc: null
  value: efficientnet-b2
